# Generated by Django 4.2.8 on 2024-05-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_best_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.IntegerField(default=0),
        ),
    ]
