# Generated by Django 4.2.8 on 2024-05-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_genre_remove_movie_genre_alter_movie_popularity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
    ]
