# Generated by Django 4.2.8 on 2024-05-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_movie_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='movie',
        ),
        migrations.AddField(
            model_name='person',
            name='movies',
            field=models.ManyToManyField(related_name='persons', to='movie.movie'),
        ),
    ]
