# Generated by Django 4.2.8 on 2024-05-23 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_remove_person_movie_person_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='movies',
        ),
        migrations.AddField(
            model_name='person',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.movie'),
            preserve_default=False,
        ),
    ]
