# Generated by Django 4.2.8 on 2024-05-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_post_click_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
